### PR TITLE
Do not quote argument if argument doesn't contain whitespace

### LINKED ISSUE #59: Incorrect argument quoting on Windows
Yeah. I'm also speechless. Apparently on Windows you **MUSTN'T** quote too little or too much.

```c
#include <stdio.h>
#include <stddef.h>
#include <malloc.h>
#include "subprocess.h"

int main() {
        const char *cmd[] = { "cmd", "/c", "echo hello", NULL };
        struct subprocess_s sub;
        int r = subprocess_create(cmd, 0, &sub);
        FILE *p = subprocess_stderr(&sub);
        char bruh[32];
        while (fgets(bruh, 32, p)) {
                printf("%s\n", bruh);
        }
        int pr;
        subprocess_join(&sub, &pr);
        return 0;
}
```

The code is a bit messy, but its obvious this is your typical run of the mill `echo` example adapted for Windows.
The only problem is it doesn't work.

Apparently `cmd.exe` **doesn't like its flags to be quoted**. This library quotes every argument, so something from the above example would produce `"cmd" "/c" "echo hello world"`. Perfectly fine for you and me (and sh), but for cmd... it interpreted `"/c" 
 "echo hello world"` as `/c "\"echo hello world"`! Suddenly there's an extra quote there. The solution is apparently
 ```c
const char *cmd[] = { "cmd", "/c echo hello", NULL };
```

This entire thing is just mind-boggling. 
Apparently [the gold standard][1]'s `force` parameter is actually important! The only way I see to fix this problem is to not quote unescaped parameter, but I am not entirely sure (also pretty hard to do).

EDIT: some potential fixes:
```diff
454a455
>   int need_quoting;
625,626c626,631
<     // For the ' ' and two '"' between items and trailing '\0'
<     len += 3;
---
>     // For the trailing \0
>     len++;
>
>     // Quote the argument if it has space or tabs in it
>     if (strpbrk(commandLine[i], "\t\v ") != NULL)
>       len += 2;
659c664,668
<     commandLineCombined[len++] = '"';
---
>
>     need_quoting = strpbrk(commandLine[i], "\t\v ") != NULL;
>     if (need_quoting) {
>       commandLineCombined[len++] = '"';
>     }
678c687,690
<     commandLineCombined[len++] = '"';
---
>
>     if (need_quoting) {
>       commandLineCombined[len++] = '"';
>     }
```

[1]: https://docs.microsoft.com/en-gb/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way

### PR DESCRIPTION
**Pull request by takase1121**
The solution proposed in #59 

Fixes #59

### CODE REVIEW

**Comment by sheredom** [comment]
Is there a way to provide a test case that this fix would ensure worked? I don't want to regress this behaviour again in future!

**Comment by takase1121** [comment]
Here is a simple test case I can think of:
```c
const char *command_line[] = { "cmd", "/c", "echo hello world", NULL }
```

When the old behavior is used cmd will throw an error, while this PR would print hello world. 

I'm not too sure how to add that to the test harness though.

**Comment by sheredom** [comment]
This will need a test case. Easiest way I can think is to add a variant of https://github.com/sheredom/subprocess.h/blob/master/test/process_return_argv.c which returns the `strlen` of `argv[1] + argv[2]`, and then call it with command line `{"process_return_argv_lens", "will be quoted", "will_not_be_quoted", 0}`.

Thoughts?

**Comment by takase1121** [comment]
This is a Windows specific test case, how about printing back `GetCommandLineA` in `process_return_argv` and then check if the argument is properly quoted?

**Comment by takase1121** [comment]
> This will need a test case. Easiest way I can think is to add a variant of https://github.com/sheredom/subprocess.h/blob/master/test/process_return_argv.c which returns the `strlen` of `argv[1] + argv[2]`, and then call it with command line `{"process_return_argv_lens", "will be quoted", "will_not_be_quoted", 0}`.
> 
> Thoughts?

I'm unsure if this would work. If a program is linked with MSVCRT, [these rules](https://docs.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments?view=msvc-170) are followed. 
If a program uses `CommandLineToArgvW`, [these slightly different rules](https://docs.microsoft.com/en-us/previous-versions/17w5ykft(v=vs.85)) are followed.
Lastly, DOS and legacy Windows applicationes **DOES NOT** follow any of these conventions (which is the headache point about that cmd example). They parse the entire lpCmdline however they want.

**Comment by takase1121** [comment]
I added a test case for this PR; basically a helper process `process_return_lpcmdline` will return the result from `GetCommandLineA` verbatim. The output is compared from the back so that it skips the executable name.

The temp array was set to 32767 because that was the maximum length of `lpCmdline`. For non-Windows part of the test, the argument is simply quoted (not properly escaped) so the test _should_ pass most of the time.

**Comment by sheredom** [comment]
Great work, thanks!

**Pull request merged**
